[feat] buttons and inputs style effect
LimongiVirgil/Architech pull request #52
Opened 2021-07-26 15:35 UTC by Pierre-Alain8

2021-07-26 19:43 UTC, Thomasevano requested changes

2021-07-26 19:43 UTC, Thomasevano commented on src/components/atoms/button/button.scss
> +
```suggestion
border: 2px solid transparent
```
en ligne 4 et ajouter `cursor: pointer` ligne 5

**Question:** il y est besoin du active ?

**Suggestion:** a voir si il est possible de faire une class/mixin commune pour éviter de répéter le meme code

2021-07-26 19:43 UTC, Thomasevano commented on src/components/atoms/datePicker/datePicker.scss
> +    border-radius: $regular-radius;
```suggestion
```
Pas obliger de remettre le meme border radius si il change pas

2021-07-26 19:43 UTC, Thomasevano commented on src/components/atoms/datePicker/datePicker.scss
> +    border-radius: $regular-radius;
```suggestion
```
Idem

2021-07-26 19:43 UTC, Thomasevano commented on src/components/atoms/datePicker/datePicker.scss
> +    border: 2px solid $gray-lighter;
pas besoin de focus je pense la couleur change pas et les 2 px creer un decalage

2021-07-26 19:43 UTC, Thomasevano commented on src/components/atoms/datePicker/datePicker.scss
> +}
**Question:** Vraiment besoins de ca ?

et pas de ligne de retour a la fin

2021-07-26 19:43 UTC, Thomasevano commented on src/components/atoms/inputTextArea/inputTextArea.scss
> +  }
Idem que input time

2021-07-26 19:43 UTC, Thomasevano commented on src/components/atoms/inputTime/inputTime.scss
> +    }
Idem que input time

2021-07-26 19:43 UTC, Thomasevano commented on src/components/molecules/calendarContactCard/calendarContactCard.scss
> +    border-bottom: 1px solid $gray-lighter;
C'est un rollback ca 🤔

2021-07-26 19:43 UTC, Thomasevano commented on src/components/molecules/calendarContactCard/calendarContactCard.scss
> +      p{
```suggestion
      p {
```

2021-07-26 19:43 UTC, Thomasevano commented on src/components/molecules/calendarContactCard/calendarContactCard.scss
> +      border: 2px solid $gray-lighter;
meme probleme avec les border a 2px et meme question sur le active

2021-07-26 19:43 UTC, Thomasevano commented on src/components/molecules/inputAndLabel/inputAndLabel.scss
> +
```suggestion

```
espace en trop

2021-07-26 19:43 UTC, Thomasevano commented on src/components/organisms/newInterventionForm/newInterventionForm.scss
> +
```suggestion

```

2021-07-26 19:43 UTC, Thomasevano commented on src/components/organisms/calendarDisclosure/calendarDisclosure.scss
> +      }
Idem

2021-07-26 19:43 UTC, Thomasevano commented on src/components/organisms/dasboardDisclosure/disclosureTypesIssues.scss
> +
Idem

2021-07-26 20:13 UTC, Pierre-Alain8 commented on src/components/atoms/button/button.scss
> +
J'ai reproduit ce qu'il avait sur la maquette, à voir avec les autres, mais si cela n'est pas nécessaire je peux le retirer.

Je vais voir pour la suggestion.

2021-07-26 20:14 UTC, Pierre-Alain8 commented on src/components/atoms/datePicker/datePicker.scss
> +    border-radius: $regular-radius;
Ok je procède à la suppression de cette ligne, car effectivement pas nécessaire finalement.

2021-07-26 20:16 UTC, Pierre-Alain8 commented on src/components/atoms/datePicker/datePicker.scss
> +    border: 2px solid $gray-lighter;
je vais retirer le focus, le décalage est trop visible

2021-07-26 20:39 UTC, Pierre-Alain8 commented on src/components/molecules/calendarContactCard/calendarContactCard.scss
> +      border: 2px solid $gray-lighter;
Pour la question sur l’active, je le mets cela en commentaire en attendant d'autres retours

2021-07-26 20:43 UTC, Pierre-Alain8 commented on src/components/organisms/calendarDisclosure/calendarDisclosure.scss
> +      }
Idem vis-à-vis de la question sur l’active, je le mets cela en commentaire en attendant d'autres retour

2021-07-26 20:44 UTC, Pierre-Alain8 commented on src/components/organisms/dasboardDisclosure/disclosureTypesIssues.scss
> +
Idem vis-à-vis de la question sur l’active, je le mets cela en commentaire en attendant d'autres retour

2021-07-26 20:48 UTC, Pierre-Alain8 commented on src/components/atoms/datePicker/datePicker.scss
> +}
Pour l'icone qui est présent par défaut dans l'input je ne pense pas finalement

2021-07-27 07:07 UTC, ETombuyses commented on src/components/atoms/button/button.scss
je pense qu'il manque un 
```suggestion
border: 2px solid transparent;
```
si tu vas dans le formulaire, les boutons "sautent" quand tu les hover parce qu'ils prennent une border d'un coup. Du coup pas besoin de le rajouter dans &--primary (suggestion thomas) parce qu'ils en ont tous besoin

2021-07-27 07:09 UTC, ETombuyses commented on src/styles/_colors.scss
> +$red-lighter: #FEFAFA;;
à renommer comme Kalani: alert et alert-light

2021-07-27 07:16 UTC, ETombuyses commented on src/components/molecules/calendarContactCard/calendarContactCard.scss
> +    }
à mon avis l'élément div ne peut pas avoir de :focus d'après MDN. Je pense que si tu passes la <div> en <button> on le verrait.

2021-07-27 07:17 UTC, ETombuyses commented on src/components/molecules/calendarContactCard/calendarContactCard.scss
> +    // }
c'était pas bon ?

2021-07-27 07:18 UTC, ETombuyses commented on src/components/organisms/calendarDisclosure/calendarDisclosure.scss
>        border: none;
il faut mettre une border de base sinon ça fait décaler l'élément dans la page au hover
```suggestion
      border: 1px solif transparent;
```

2021-07-27 07:20 UTC, Pierre-Alain8 commented on src/components/molecules/calendarContactCard/calendarContactCard.scss
> +    }
Je vais le supprimer alors si ce n'est pas recommandé, j'aurais du faire plus attention

2021-07-27 07:21 UTC, ETombuyses commented on src/components/organisms/dasboardDisclosure/disclosureTypesIssues.scss
> +
le css doit être exactement le même que ton autre disclosure de l'agenda sinon ça n'a pas de sens. Tu peux limite en faire un component à part sauf si ça te prends trop de temps, il faut juste harmoniser l'effet visuel du bouton

2021-07-27 07:21 UTC, Thomasevano commented on src/components/molecules/calendarContactCard/calendarContactCard.scss
> +    // }
je crois que c'est par rapport a mes retour, je me demandais si on avait besoins de active ?!

2021-07-27 07:21 UTC, Pierre-Alain8 commented on src/components/molecules/calendarContactCard/calendarContactCard.scss
> +    // }
C'était par rapport au questionnement de Thomas sur l'utilité de l'active, je l'avais mis en commentaire en attendant vos retours sur son utilité

2021-07-27 07:24 UTC, ETombuyses commented on src/components/molecules/calendarContactCard/calendarContactCard.jsx
> +      </div>
il manque une beorder top, bottom et right pour que ce soit comme sur les maquettes

2021-07-27 07:24 UTC, Pierre-Alain8 commented on src/components/organisms/dasboardDisclosure/disclosureTypesIssues.scss
> +
Non ça va, je vais appliquer le même css sur les autres disclosures

2021-07-27 07:24 UTC, ETombuyses commented on src/components/atoms/inputTime/inputTime.scss
> +}
saut de ligne manquant

2021-07-27 07:27 UTC, ETombuyses commented on src/components/atoms/datePicker/datePicker.scss
> +}
saut de ligne manquant

2021-07-27 07:30 UTC, Pierre-Alain8 commented on src/components/atoms/inputTime/inputTime.scss
> +}
Thomas m'avait dit de les retirer 🤔

2021-07-27 07:30 UTC, ETombuyses commented on src/components/atoms/datePicker/datePicker.scss
> +    border: 2px solid $gray-lighter;
j'aurais gardé la meêm couleur que le :hover, sinon on voit pas bien l'effet en gris. Il te manque également un 
```suggestion
    outline: none;
```
sinon les browser vont override ton effet

2021-07-27 07:34 UTC, ETombuyses reviewed
Commentaire général.
- ajouter un ```cursor: pointer; ``` sur tous les éléments clicables (input textarea, date, time, bouton pour ajouter un event...)
- ajouter une border transparente de base aux éléments qui en ont au :hover :focus ou :active
- ajouter un ```outline: none;``` sur les inputs (textarea, date, time) sinon ton effet de focus est écrasé + passer la couleur de l'effet de focus des input en primary sinon on ne voit pas l'effet

2021-07-27 07:54 UTC, Thomasevano commented on src/components/atoms/datePicker/datePicker.scss
> +}
```suggestion
}

```
Manque un retour a la ligne

2021-07-27 07:54 UTC, Thomasevano commented on src/components/atoms/inputTextArea/inputTextArea.scss
> +}
```suggestion
}

```
manque un retour a la ligne

2021-07-27 07:54 UTC, Thomasevano commented on src/components/atoms/inputTime/inputTime.scss
> +}
```suggestion
}

```
manque un retour a la ligne

2021-07-27 07:54 UTC, Thomasevano commented on src/components/atoms/inputTime/inputTime.scss
> +      border-radius: $regular-radius;
```suggestion
```
Pa besoin d'overwrite le `border-radius` s'il il change pas

2021-07-27 07:54 UTC, Thomasevano commented on src/components/atoms/inputTime/inputTime.scss
> +      border-radius: $regular-radius;
```suggestion
```
Same pour le`border-radius`

2021-07-27 07:54 UTC, Thomasevano commented on src/components/atoms/button/button.scss
> +      border-radius: $regular-radius;
**Suggestion:** `border-radius` de base au lieu de le rajouter a chaque et je crois que ca creer un decalage

2021-07-27 07:54 UTC, Thomasevano commented on src/components/molecules/calendarContactCard/calendarContactCard.scss
> +    border-right: none;
Regression ca non ?!

2021-07-27 08:04 UTC, ETombuyses approved these changes

2021-07-27 08:11 UTC, Pierre-Alain8 commented on src/components/atoms/datePicker/datePicker.scss
> +}
Déjà ajouté

2021-07-27 08:26 UTC, LimongiVirgil commented on src/components/atoms/button/Button.jsx
> +    <button className={
indentatiob

2021-07-27 08:30 UTC, LimongiVirgil requested changes

2021-07-27 08:30 UTC, LimongiVirgil commented on src/components/atoms/button/Button.jsx
> +    <button className={
a regarder dans le code si bien indanter

2021-07-27 09:07 UTC, Thomasevano approved these changes

2021-07-27 09:07 UTC, LimongiVirgil approved these changes

2021-07-27 09:08 UTC, merged